#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# change-port.sh  —  Change the TCP port for the supervisor-check application
#
# Usage:
#   ./change-port.sh              → show current port
#   ./change-port.sh <port>       → switch to <port> and restart the service
#   ./change-port.sh 80           → revert to default
#
# Examples:
#   ./change-port.sh 8080
#   ./change-port.sh 443
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SERVICE="supervisor-check"
OVERRIDE_DIR="/etc/systemd/system/${SERVICE}.service.d"
OVERRIDE_FILE="${OVERRIDE_DIR}/port.conf"

# ── Helper: current port ──────────────────────────────────────────────────────
current_port() {
    grep -s 'SUPERVISOR_CHECK_PORT' "$OVERRIDE_FILE" 2>/dev/null \
        | sed 's/.*=//;s/[[:space:]]//g' \
        || echo "80"
}

# ── No argument: just show current port ──────────────────────────────────────
if [[ $# -eq 0 ]]; then
    echo "Current port : $(current_port)"
    echo ""
    echo "Usage: $0 <port>"
    exit 0
fi

NEW_PORT="$1"

# ── Validate ──────────────────────────────────────────────────────────────────
if ! [[ "$NEW_PORT" =~ ^[0-9]+$ ]]; then
    echo "Error: '$NEW_PORT' is not a valid number." >&2
    exit 1
fi
if (( NEW_PORT < 1 || NEW_PORT > 65535 )); then
    echo "Error: port must be between 1 and 65535." >&2
    exit 1
fi
if (( NEW_PORT < 1024 )); then
    echo "Note: port $NEW_PORT is a privileged port (<1024). The service runs as root — OK."
fi

OLD_PORT=$(current_port)

# ── Write systemd drop-in override ───────────────────────────────────────────
mkdir -p "$OVERRIDE_DIR"
cat > "$OVERRIDE_FILE" <<EOF
# Generated by change-port.sh — do not edit manually.
[Service]
Environment=SUPERVISOR_CHECK_PORT=${NEW_PORT}
EOF

systemctl daemon-reload
systemctl restart "$SERVICE"
sleep 1

# ── Result ────────────────────────────────────────────────────────────────────
STATUS=$(systemctl is-active "$SERVICE")
if [[ "$STATUS" == "active" ]]; then
    echo "✓  Port changed  $OLD_PORT  →  $NEW_PORT"
    echo "✓  Service is active."
else
    echo "✗  Service is '$STATUS' after restart." >&2
    echo "   Check logs: journalctl -u $SERVICE -n 30" >&2
    exit 1
fi
